import "dotenv/config";
import request from "supertest";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import app from "../src/app.js";
import { getPrismaClient } from "../src/config/database.js";

const prisma = getPrismaClient(); let users: string[] = []; let rooms: string[] = []; let drafts: string[] = [];
async function setup() { const a = await prisma.user.create({ data: { name: "Draft Owner" } }); const b = await prisma.user.create({ data: { name: "Other" } }); users.push(a.id, b.id); const room = await prisma.room.create({ data: { code: `D${a.id.slice(-5).toUpperCase()}`, ownerId: a.id } }); rooms.push(room.id); await prisma.roomMember.createMany({ data: [{ roomId: room.id, userId: a.id, status: "ACTIVE" }, { roomId: room.id, userId: b.id, status: "ACTIVE" }] }); return { a, b, room }; }
afterEach(async () => { if (rooms.length) { await prisma.sharedDraft.deleteMany({ where: { roomId: { in: rooms } } }); await prisma.roomMember.deleteMany({ where: { roomId: { in: rooms } } }); await prisma.room.deleteMany({ where: { id: { in: rooms } } }); } if (drafts.length) await prisma.draft.deleteMany({ where: { id: { in: drafts } } }); if (users.length) await prisma.user.deleteMany({ where: { id: { in: users } } }); users=[]; rooms=[]; drafts=[]; }); afterAll(async()=>prisma.$disconnect());
describe("Draft APIs", () => {
  it("creates, lists, gets, and deletes draft metadata", async () => { const { a } = await setup(); const created = await request(app).post("/api/drafts").send({ userId:a.id,name:"Echo take",filePath:"/local/take.wav",durationMs:1200 }); expect(created.status).toBe(201); drafts.push(created.body.id); expect((await request(app).get(`/api/drafts?userId=${a.id}`)).body).toHaveLength(1); expect((await request(app).get(`/api/drafts/${created.body.id}`)).status).toBe(200); expect((await request(app).delete(`/api/drafts/${created.body.id}`)).status).toBe(204); drafts=[]; });
  it("validates drafts and shares metadata only once", async () => { const { a, b, room } = await setup(); expect((await request(app).post("/api/drafts").send({ userId:a.id,name:"",filePath:"",durationMs:0 })).status).toBe(400); const draft = await prisma.draft.create({ data:{ userId:a.id,name:"Take",filePath:"/take.wav",durationMs:1 } }); drafts.push(draft.id); const first=await request(app).post(`/api/rooms/${room.id}/drafts/share`).send({userId:a.id,draftId:draft.id}); expect(first.status).toBe(201); expect(first.body.duplicate).toBe(false); const duplicate=await request(app).post(`/api/rooms/${room.id}/drafts/share`).send({userId:a.id,draftId:draft.id}); expect(duplicate.body.duplicate).toBe(true); expect((await request(app).post(`/api/rooms/${room.id}/drafts/share`).send({userId:b.id,draftId:draft.id})).status).toBe(403); });
});
